#! /usr/bin/env bash
set -e
CURL_OUTPUT_FILE=$(mktemp)
trap "rm -f ${CURL_OUTPUT_FILE}" EXIT
HTTP_STATUS="$(curl --connect-timeout 1 -s -S "http://services.glgresearch.com/notify/ping/receive" -H 'Content-Type: application/json' --data-binary '{"source":"bottle/ping"}' --write-out '%{http_code}' -o "${CURL_OUTPUT_FILE}")"
SEND_RESULT=$?
# output the result of our curl, regardless of the result
cat ${CURL_OUTPUT_FILE}
if [ ${SEND_RESULT} -ne 0  -o ${HTTP_STATUS} -ne 200 ]; then
  if [ -n "https://services.glgresearch.com/notify/send" ]; then
    if printf "bottle/ping" | grep -E 'bottle\/push\/error'; then
      # if the message we failed to push is the message indicating a failure to push, we 
      # MUST NOT SEND IT, lest we DoS ourselves
      :
    else
      curl --connect-timeout 1 -s -S "https://services.glgresearch.com/notify/send" -H 'Content-Type: application/json' --data '{"source":"bottle/push/error","notifyUrl":"http://services.glgresearch.com/notify/ping/receive"}'
    fi
  fi
  exit 1
fi
