#! /usr/bin/env bash
# vim:ft=sh

WALK_PATH=${1?You need to provide a path to walk}

function walkBack(){
  CHECK_DIR=${1?No path provided to walk}
  while [ -n "${CHECK_DIR}" -a "${CHECK_DIR}" != "/" -a "${CHECK_DIR}" != "." ]; do
    echo ${CHECK_DIR}
    CHECK_DIR=$(dirname ${CHECK_DIR})
  done
}

walkBack ${WALK_PATH}
